### ISSUE TITLE
Unable to create Data object

### ISSUE THREAD

**Issue by cullanhowlett** [steven-murray/pydftools#1]
* pydftools version: 0.1.0
* Python version: 3.7
* Operating System: MacOSX

### Description
Hi Steven, I tried reproducing the Tutorial 1 example in the documentation, but was not able to create a Data class object on the line:
```data=df.Data(x=x, x_err=x_err)```

I think the fix is that the "Data" class needs importing in the __init__.py file: i.e., ```from .dffit import DFFit, Data```

Thanks,
Cullan

**Comment by steven-murray** [comment]
Thanks @CullanHowlett! I'd say the problem is that I wrote this for Python2. I'll fix that shortly.

**Comment by steven-murray** [comment]
@CullanHowlett can you check the `py3` branch and whether it works for you?

**Comment by cullanhowlett** [comment]
I installed the py3 branch from source and it still reports: module 'pydftools' has no attribute 'Data'

**Comment by steven-murray** [comment]
Ah yes, my mistake. It's fixed now.
